services:
  web:
    # Note that the build context and Dockerfile are specified in the override files for dev and prod environments individually.
    build: .
    command: bundle exec rails s -b '0.0.0.0'
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - POSTGRES_HOST=db
    env_file: ".env"
    
  db:
    image: postgres:latest
    env_file: ".env"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

#     "Statt mounten würde man auf Deutsch montieren sagen. 
#      Wörtlich übersetzt heißt das zwar eigentlich reiten, aber kein Mensch reitet seinen PC." 
#       ~ Prof. Baumgartl