services:
  web:
    build: .
    command: bundle exec rails s -b '0.0.0.0'
    ports:
      - "3000:3000"
    # depends_on:
    #   - db
    environment:
      - RAILS_ENV=development
      - DEFAULT_USER_USERNAME=admin
      - DEFAULT_USER_PASSWORD=123
    #env_file: "webapp.env"
    volumes:
      - ./:/rails:rw
      #     "Statt mounten würde man auf Deutsch montieren sagen. 
      #      Wörtlich übersetzt heißt das zwar eigentlich reiten, aber kein Mensch reitet seinen PC." 
      #       ~ Prof. Baumgartl

#   db:
#     image: postgres:latest
#     secrets:
#       - db-password
#     environment:
#       - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
#     volumes:
#       - postgres_data:/var/lib/postgresql/data

# volumes:
#   postgres_data:
# secrets:
#   db-password:
#     file: db/password.txt
